apiVersion: v1
appVersion: 0.3.0
description: React to the events from Falco
name: falco-talon
version: 0.3.1
keywords:
  - falco
  - monitoring
  - security
  - response-engine
home: https://github.com/falcosecurity/falco-talon
sources:
  - https://github.com/falcosecurity/falco-talon
maintainers:
  - name: Issif
    email: issif+github@gadz.org
  - name: IgorEulalio
    email: igoreulalio.ie@gmail.com
